name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to DigitalOcean Container Registry
      run: echo "${{ secrets.DO_PASSWORD }}" | docker login ${{ secrets.DO_REGISTRY }} -u ${{ secrets.DO_USERNAME }} --password-stdin
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/baas-schema:latest
        docker push ${{ secrets.DOCKER_REGISTRY }}/baas-schema:latest
